### PR TITLE
RK-12380 - Added a dev container

### PR DESCRIPTION
**Pull request by Urook**
Added a dev container

### CODE REVIEW

**Comment by Urook** [comment]
Github Enforcer opened Task: [RK-12380](https://rookout.atlassian.net/browse/RK-12380)

**Review by eli-hatamov-dt — COMMENTED** [review]
Does the `Dockerfile` overrides the `devcontainer.json`? cause it seems like there are different values for the same arguments in those files. For example `INSTALL_MAVEN` and `INSTALL GRADLE` have `true` in `devcontainer.json` but `false` in the `Dockerfile` (it's confusing)

**Comment by Urook** [comment]
> Does the `Dockerfile` overrides the `devcontainer.json`? cause it seems like there are different values for the same arguments in those files. For example `INSTALL_MAVEN` and `INSTALL GRADLE` have `true` in `devcontainer.json` but `false` in the `Dockerfile` (it's confusing)

It should override them

**Comment by Urook** [comment]
@EliRookout Should I change it in Dockerfile for clarification's case?

**Comment by eli-hatamov-dt** [comment]
> @EliRookout Should I change it in Dockerfile for clarification's case?

I think you should modify the `devcontainer.json` to have the same values as in the `Dockerfile` it would be less confusing

**Comment by Urook** [comment]
@EliRookout Done

**Review by eli-hatamov-dt — APPROVED** [review]

**Pull request merged**
