### PR TITLE
RK-8742 - Added steps for setting up Jaegar

### PR DESCRIPTION
**Pull request by jhendrick**

### CODE REVIEW

**Comment by jhendrick** [comment]
Github Enforcer opened Task: [RK-8742](https://rookout.atlassian.net/browse/RK-8742)

**Comment by ElDuderinos** [comment]
@jhendrick That's an update long overdue that is much needed :)
Maybe also add something about the option of running without Jaeger enabled?
(using opentracing.jaeger.enabled=false - https://github.com/opentracing-contrib/java-spring-jaeger#completely-disable-tracing)
I think that setting that in the application.properties file might be enough

**Comment by jhendrick** [comment]
@ElDuderinos I gave that a try but it doesn't seem to work. Strange enough, if I just change:

opentracing.jaeger.udp-sender.host=jaeger-agent
opentracing.jaeger.udp-sender.port=6831

to 

opentracing.jaeger.udp-sender.host=localhost
opentracing.jaeger.udp-sender.port=6831

Then the application starts correctly (even if the Jaegar agent isn't running). But in either case, it looks like no tracing data is pulled in to Rookout, although I do see the tracing data in the Jaegar UI.

**Review by ElinorSwery — CHANGES_REQUESTED** [review]
Got everything working with the changes you added.

We need to add a section on the server selection step.
Breakpoint description is outdated. Feel free to use the updated description here https://github.com/Rookout/tutorial-python (note I need to update the server selection step in there)

**Review by jhendrick — COMMENTED** [review]
Updated usage steps

**Review by ElinorSwery — APPROVED** [review]

**Pull request merged**
